### ISSUE TITLE
Performance gap in code reproduction

### ISSUE THREAD

**Issue by Bruce-GuoS** [iSEE-Laboratory/VersReID#3] opened 2024-04-25 07:11 UTC
Hi, thanks for your awesome work.
I met some problems when trying to reproduce your results, and I hope to get your help. I used the default settings in configs/ReID-Bank.yml and V-Branch.yml without changing for training these two models. The performance gaps are much larger on PRCC and SYSU-mm01. Please see the performances listed in the table:
![image](https://github.com/iSEE-Laboratory/VersReID/assets/34935711/cf2c674b-f76e-43c5-985c-ef22bb90356d)

I wonder what cause the performance drops, it is configurations or pre-trained model? I attach my training logs for your reference. I look forward to your reply, thank you.
[ReID-Bank_train.txt](https://github.com/iSEE-Laboratory/VersReID/files/15105712/ReID-Bank_train.txt)

**Comment by Bruce-GuoS** [comment] 2024-04-25 07:13
The log is missing. I upload it again.
[ReID-Bank_train.txt](https://github.com/iSEE-Laboratory/VersReID/files/15105743/ReID-Bank_train.txt)

**Comment by yanjk3** [comment] 2024-04-27 14:35
I am currently busy with some other shits and will try to figure it out within two weeks.

**Comment by Bruce-GuoS** [comment] 2024-04-28 02:19
Thank you in advance for your kindly help!

**Comment by yanjk3** [comment] 2024-05-07 11:48
After some tries, I found the problem lies in the evaluation protocols of the PRCC and SYSU-MM01 datasets, which adopt a single-shot setting. Although the final result is the average performance over ten trials, it still fluctuates since the number of identities is small, and the fluctuation may be really sharp sometimes (±5.0% or more). Currently, I have no idea how to make the performance of PRCC and SYSU-MM01 stable, and I think their evaluation protocols are unreasonable to some extent. But to compare ours with previous arts, we still need to follow these protocols.

**Comment by Bruce-GuoS** [comment] 2024-05-14 10:51
Thank you for your response.  The evaluation protocols is one of the reasons. In my experiments, the version of CUDA can affect the performance.  CUDA 10.2 can achieve better reproducibility than CUDA11.0 or CUDA11.3. Have you tried on other version of CUDA? Why the version of CUDA affect the performance, is it because the pretrained model is trained on CUDA10.2? Thank you.

**Comment by yanjk3** [comment] 2024-05-14 11:08
Have no idea about that. I remembered I had seen [this link](https://github.com/WangTaoAs/PFD_Net/issues/3#issuecomment-1002036261), and then I decided to use CUDA 10.2. And that's why I recommend using CUDA 10.2 for reproduction.

**Comment by Bruce-GuoS** [comment] 2024-05-14 11:11
I got it. Thank you for your response.

**Comment by yanjk3** [comment] 2024-05-14 11:16
Close it now and if there are any other questions plz let me know or reopen it~

**Closed as completed by yanjk3** 2024-05-14 11:16 UTC

**Comment by LiuYuan84** [comment] 2025-03-07 00:10
hi I am so sorry to bother you,could you please tell me where your transformer_120.pth get and how is your prcc dataset organized? I am a freshman in this area,I cannot find them😭
